clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  test:
    image: golang:1.10.3-alpine
    commands:
      - export PACKAGE="$(go env GOPATH)/src/github.com/ntrrg/ntgo"
      - mkdir -p $(dirname $PACKAGE)
      - ln -sf "$PWD" "$PACKAGE"
      - cd "$PACKAGE" && make ci
