clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  test:
    image: ntrrg/ntgo
    commands:
      - export PACKAGE="$(go env GOPATH)/src/github.com/ntrrg/ntgo"
      - ln -sf "$PWD" "$PACKAGE"
      - cd "$PACKAGE"
      - make ci
