image: golang:1.10.3-alpine
before_script:
  - apk update && apk add git make
test:
  script:
    - export BASEDIR="$(go env GOPATH)/src/github.com/ntrrg"
    - mkdir -p "$BASEDIR"
    - ln -sf "$PWD" "$BASEDIR/ntgo"
    - cd "$BASEDIR/ntgo"
    - make deps
    - make ci
