run:
  tests: true
  timeout: 1m
  skip-dirs: []
  skip-files: []
linters:
  enable-all: true
  disable:
    - depguard
    - exhaustivestruct
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godox
    - goerr113
    - gofumpt
    - golint
    - gomnd
    - ifshort
    - interfacer
    - maligned
    - nlreturn
    - scopelint
    - unparam
    - unused
linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 10.0
    skip-tests: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocognit:
    min-complexity: 10
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: true
  lll:
    line-length: 79
  misspell:
    locale: US
  nestif:
    min-complexity: 3
  wsl:
    strict-append: true
    allow-assign-and-call: true
    allow-assign-and-anything: false
    allow-multiline-assign: false
    force-case-trailing-whitespace: 0
    allow-cuddle-declarations: false
    allow-case-trailing-whitespace: true
    allow-trailing-comment: false
    enforce-err-cuddling: true
issues:
  exclude-rules:
    - source: "^//"
      linters:
        - lll
    - path: "_test\\.go"
      linters:
        - cyclop
        - dupl
        - gocognit
        - forbidigo
        - funlen
        - lll
        - testpackage
        - wrapcheck

