os: linux
dist: xenial
git:
  depth: 1
language: go
go: "1.11.5"
env:
  - GO111MODULE=on
jobs:
  include:
    - script: ./mage -v test
    - stage: "QA"
      name: "Linting"
      script: ./mage -v lint
    - name: "Tests coverage"
      script: ./mage -v coverage:default
    - name: "Benckmarks"
      script: ./mage -v benchmark
    - stage: "Build"
      script: ./mage -v build
after_success:
  - bash <(curl -s https://codecov.io/bash)

