os: linux
dist: xenial
git:
  depth: 1
language: go
go:
  - "1.11"
  - "1.12"
env:
  - GO111MODULE=on
before_install:
  - wget 'https://github.com/golangci/golangci-lint/releases/download/v1.16.0/golangci-lint-1.16.0-linux-amd64.tar.gz' &&
    tar -xf golangci-lint-1.16.0-linux-amd64.tar.gz &&
    mkdir -p "$GOPATH/bin" &&
    cp -f golangci-lint-1.16.0-linux-amd64/golangci-lint "$GOPATH/bin" &&
    chmod +x "$GOPATH/bin/golangci-lint" &&
    rm -rf golangci-lint-1.16.0-linux-amd64*
jobs:
  include:
    - script: ./mage -v test:race
    - stage: "QA"
      name: "Linting"
      script: ./mage -v lint
    - name: "Code Analysis"
      script: ./mage -v ca
    - name: "Tests coverage"
      script: ./mage -v coverage:default
    - name: "Benckmarks"
      script: ./mage -v benchmark
    - stage: "Build"
      script: ./mage -v build
after_success:
  - bash <(curl -s https://codecov.io/bash)

