name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Integration
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go_version:
          - "1.18"
          - "1.19"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Set up tools
        run: |
          wget -qO "/tmp/golangci-lint-1.47.3-linux-amd64.tar.gz" 'https://github.com/golangci/golangci-lint/releases/download/v1.47.3/golangci-lint-1.47.3-linux-amd64.tar.gz'
          tar -xf "/tmp/golangci-lint-1.47.3-linux-amd64.tar.gz" -C "/tmp/"
          sudo cp "/tmp/golangci-lint-1.47.3-linux-amd64/golangci-lint" "/usr/bin/"

      - name: Get source code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Tests
        run: make test-race

      - name: Coverage
        run: |
          make coverage-check
          mv coverage-dev.txt coverage.txt
          bash <(curl -s https://codecov.io/bash)

      #- name: Benchmarks
      #  run: make benchmark-check

      - name: Lint
        run: make lint

      - name: Code Analysis
        run: make ca

