name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: CI
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go_version:
          - "1.13"
          - "1.14"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Set up tools
        run: |
          export GO111MODULE="on"
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.21.0

      - name: Get source code
        uses: actions/checkout@v2

      - name: Lint
        run: make lint

      - name: Tests
        run: make test-race

      - name: Code Analysis
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make ca

      - name: Coverage
        run: |
          make coverage
          bash <(curl -s https://codecov.io/bash)

      - name: Build
        run: make build

      - name: Benchmarks
        run: make benchmark

